"""empty message

Revision ID: a4a913a822ab
Revises: e7bd343b80c4
Create Date: 2024-10-04 14:21:33.340357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a913a822ab'
down_revision = 'e7bd343b80c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pins', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pins', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=4000),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
